apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-cfg
data:
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
  AIRFLOW__CORE__LOAD_EXAMPLES: 'true'
  AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth'
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-db:5432/airflow
  AIRFLOW__WEBSERVER__SECRET_KEY: CQrj1tjV2249zQ5Xhuw
  AIRFLOW__CORE__FERNET_KEY: eUxiQ4NXh-Y7NXmnUZ8N6qs_0RomoSjyE8b3UMZZ4TE=
  AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
  AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
