apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-init-db
spec:
  template:
    spec:
      containers:
        - name: airflow-init
          image: apache/airflow:2.1.4
          args:
            - "db"
            - "init"
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://airflow:airflow@postgres-db:5432/airflow
            - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
              value: 'True'
            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: 'True'
            - name: AIRFLOW__API__AUTH_BACKEND
              value: airflow.api.auth.backend.basic_auth
            - name: AIRFLOW__WEBSERVER__SECRET_KEY
              value: 'CQrj1tjV2249zQ5Xhuw'
            - name: AIRFLOW__CORE__FERNET_KEY
              value: 'eUxiQ4NXh-Y7NXmnUZ8N6qs_0RomoSjyE8b3UMZZ4TE='
      restartPolicy: OnFailure
  backoffLimit: 5
---

apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-create-user
spec:
  template:
    spec:
      containers:
        - name: airflow-create
          image: apache/airflow:2.1.4
          args: [ "users", "create", "-e", "airflow@airflow.com", "-f", "airflow", "-l", "airflow", "-p", "airflow",
                  "-r", "Admin", "-u", "airflow" ]
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://airflow:airflow@postgres-db:5432/airflow
            - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
              value: 'True'
            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: 'True'
            - name: AIRFLOW__API__AUTH_BACKEND
              value: airflow.api.auth.backend.basic_auth
            - name: AIRFLOW__WEBSERVER__SECRET_KEY
              value: 'CQrj1tjV2249zQ5Xhuw'
            - name: AIRFLOW__CORE__FERNET_KEY
              value: 'eUxiQ4NXh-Y7NXmnUZ8N6qs_0RomoSjyE8b3UMZZ4TE='
      restartPolicy: OnFailure
  backoffLimit: 5