apiVersion: v1
kind: Service
metadata:
  name: airflow-service
spec:
  type: LoadBalancer
  selector:
    app: airflow
  ports:
    - name: air-svc-http
      targetPort: air-dep-http
      port: 8080