apiVersion: v1
kind: Pod
metadata:
  name: postgres-db
  labels:
    app: postgres
spec:
  volumes:
    - name: postgres-storage
      persistentVolumeClaim:
        claimName: postgres-pvc
  containers:
    - name: postgres
      image: postgres:14.5
      ports:
        - name: postgres-http
          containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: airflow
        - name: POSTGRES_DB
          value: airflow
      envFrom:
        - configMapRef:
            name: postgres-cfg
      volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: postgres-storage
