apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
spec:
  containers:
    - name: redis
      image: redis:7.0.5
      ports:
        - name: redis-http
          containerPort: 6379
