apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  labels:
    app: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      volumes:
        - name: dags
          emptyDir: { }
      containers:
        - name: airflow
          image: apache/airflow:2.2.3
          args:
            - scheduler
          volumeMounts:
            - name: dags
              mountPath: /opt/airflow/dags
          envFrom:
            - configMapRef:
                name: airflow-cfg
            - secretRef:
                name: airflow-secret
        - name: dagfetcher
          image: bitnami/git:2.39.1-debian-11-r8
          command:
            - sh
            - -c
            - "while true; do git clone https://github.com/iKintosh/airflow-dags.git /dags/ && cd dags/ && git pull -f && cd ..  && sleep 60; done"
          volumeMounts:
            - name: dags
              mountPath: /dags