apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-init-db
spec:
  template:
    spec:
      containers:
        - name: airflow-init
          image: apache/airflow:2.2.3
          args:
            - "db"
            - "init"
          envFrom:
            - configMapRef:
                name: airflow-cfg
            - secretRef:
                name: airflow-secret
      restartPolicy: OnFailure
  backoffLimit: 5
---

apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-init-user
spec:
  template:
    spec:
      containers:
        - name: airflow-init
          image: apache/airflow:2.2.3
          args: [ "users", "create", "-e", "airflow@airflow.com", "-f", "airflow", "-l", "airflow", "-p", "$(AIRFLOW_ADMIN_PASS)",
                  "-r", "Admin", "-u", "$(AIRFLOW_ADMIN_NAME)" ]
          envFrom:
            - configMapRef:
                name: airflow-cfg
            - secretRef:
                name: airflow-secret
      restartPolicy: OnFailure
  backoffLimit: 5