apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-cfg
data:
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
  AIRFLOW__CORE__LOAD_EXAMPLES: 'true'
  AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth'
  AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
