apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  labels:
    app: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      volumes:
        - name: dags
          emptyDir: { }
      containers:
        - name: airflow
          image: apache/airflow:2.2.3
          args:
            - scheduler
          volumeMounts:
            - name: dags
              mountPath: /opt/airflow/dags
          envFrom:
            - configMapRef:
                name: airflow-cfg
            - secretRef:
                name: airflow-secret
        - name: dagfetcher
          image: openweb/git-sync
          env:
          - name: GIT_SYNC_REPO
            value: https://github.com/iKintosh/airflow-dags.git
          - name: GIT_SYNC_BRANCH
            value: master
          - name: GIT_SYNC_REV
            value: "FETCH_HEAD"
          - name: GIT_SYNC_DEST
            value: /dags
          - name: GIT_SYNC_WAIT
            value: "30"
          - name: GIT_SYNC_ONE_TIME
            value: "false"
          volumeMounts:
            - name: dags
              mountPath: /dags