apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webservice
  labels:
    app: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      volumes:
        - name: dags
          emptyDir: { }
      containers:
        - name: airflow-webserver
          image: apache/airflow:2.1.4
          args:
            - webserver
          readinessProbe:
            httpGet:
              port: 8080
              path: /health
          volumeMounts:
            - name: dags
              mountPath: /opt/airflow/dags
          envFrom:
            - configMapRef:
                name: airflow-cfg
            - secretRef:
                name: airflow-secret
          ports:
            - name: air-webservice
              containerPort: 8080
        - name: dagfetcher
          image: bitnami/git:2.39.1-debian-11-r8
          command:
            - sh
            - -c
            - "while true; do rm -fv /dags/* && git clone https://github.com/iKintosh/airflow-dags.git && sleep 60; done"
          volumeMounts:
            - name: dags
              mountPath: /dags