apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-worker
  labels:
    app: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-worker
  template:
    metadata:
      labels:
        app: airflow-worker
    spec:
      volumes:
        - name: dags
          emptyDir: { }
      containers:
        - name: dagfetcher
          image: bitnami/git:2.39.1-debian-11-r8
          command:
            - sh
            - -c
            - "while true; do git clone https://github.com/iKintosh/airflow-dags.git /dags/ && cd dags/ && git pull -f && cd ..  && sleep 60; done"
          volumeMounts:
            - name: dags
              mountPath: /dags
        - name: airflow-worker
          image: apache/airflow:2.2.3
          command:
            - airflow
            - celery
            - worker
          ports:
            - name: air-worker
              containerPort: 8793
          volumeMounts:
            - name: dags
              mountPath: /opt/airflow/dags
          env:
            - name: "AIRFLOW__CORE__HOSTNAME_CALLABLE"
              value: 'airflow.utils.net:get_host_ip_address'
          envFrom:
            - configMapRef:
                name: airflow-cfg
            - secretRef:
                name: airflow-secret
