apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: LoadBalancer
  ports:
    - name: minio-db
      port: 9000
      protocol: TCP
    - name: minio-console
      port: 9090
  selector:
    app: minio