apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  labels:
    app: minio
spec:
  volumeClaimTemplates:
    - metadata:
        name: minio-data
      spec:
        resources:
          requests:
            storage: 5Gi
        accessModes:
          - ReadWriteOnce
  serviceName: minio
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: minio-data
      containers:
        - name: minio
          image: minio/minio:RELEASE.2023-02-10T18-48-39Z
          command:
          - /bin/bash
          - -c
          args:
          - minio server /storage --console-address :9090
          volumeMounts:
            - name: minio-data
              mountPath: /storage
          ports:
            - containerPort: 9000
              name: minio-db
            - containerPort: 9090
              name: minio-console
          env:
            - name: MINIO_ROOT_USER
              value: "minio"
          envFrom:
            - secretRef:
                name: airflow-secret